export class Player {
    id: number;
    name:string;
    first_name:string;
    last_name:string;
    position:string;
    team_abbreviation:string;
    nba_efficiency_rating: number;
    games_played: number;
    minutes: number;
    points: number;
    offensive_rebounds: number;
    defensive_rebounds: number;
    total_rebounds: number;
    assists: number;
    steals: number;
    blocks: number;
    turnovers: number;
    points_per_game: number;
    three_points_made_per_game: number;
    minutes_per_game: number;
    offensive_rebounds_per_game: number;
    defensive_rebounds_per_game: number;
    total_rebounds_per_game: number;
    assists_per_game: number;
    steals_per_game: number;
    blocks_per_game: number;
    turnovers_per_game: number;
    free_throws_made: number;
    free_throws_attempted: number;
    field_goals_made: number;
    field_goals_attempted: number;
    three_points_made: number;
    three_points_attempted: number;
    free_throw_percentage: number;
    field_goal_percentage: number;
    three_point_percentage: number;
    assist_turnover_ratio: number;
    steal_turnover_ratio: number;
    personal_fouls: number;
    disqualifications: number;
    technical_fouls: number;
    ejections: number;
    flagrant_fouls: number;
    team_city: string;
    team_name: string;
    team_long_name: string;
    conference: string;
    division: string;
    team_color: string;
    tid: number;
    feet: number;
    inches: number;
    weight: number;
    dob: string;
    birthplace: string;
    college: string;
    draft_year: string;
    round: string;
    pick: string;
    drafted_by: string
  }